logging:
  level:
    root: WARN
    projects.realestatemanager: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/final_project?useSSL=false&serverTimezone=UTC
    username: root
    password:
